### ISSUE TITLE
Eager return

### ISSUE THREAD

**Issue by zrma** [namonak/HackerRank#10]
https://github.com/namonak/HackerRank/blob/2c91f56b32dab405cf4427c889cbc3abd68de3e4/C/ForLoopinC/for_loop_in_c.c#L10

I recommend removing `else` and lowering the code depth.

```c
    if (digit % 2 == 0) {
        printf("even\n");
        return;
    }
    printf("odd\n");
```

**Comment by namonak** [comment]
오... 저런 경우 습관적으로 else 문 처리했는데 저렇게 하니까 확실히 코드가 깔끔해 지네요. 중간에 return 되니까 성능도 좋아지는 걸까요?

Principles are good, since they are based on the hard earned experience from the past, but they should never be applied blindly.

* e201497bc79c2e42bdc1279145e3cfbdc5ee5e41
* Reference : [Clean Code - Pitfalls of Eager Return](http://greyfocus.com/2015/05/clean-code-pitfalls-eager-return/)
